### ISSUE TITLE
Add radio option and buttons to storyline

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#123]
**Description**

Apart from sliders, content managers should have the option to include a radio group and button group as well according to the [design](https://xd.adobe.com/view/fdfd0445-f79f-426d-a864-c0cb70e3329b-a8ae/screen/e25723c1-e7e4-4709-90b3-8b32a0f024a8/)

![Image](https://user-images.githubusercontent.com/32770108/199434378-0e2303f4-b546-44d9-8d89-216afe5547e1.png)

**To discuss**

- How are these settings merged with the existing sliders, interactive elements or seperate categories? Interactive elements
- How are these buttons linked to input for the Anylogic model? Mapping per scenario
- Who determines the options, modellers or content managers? Options -> moddelers, visualisation -> content manager
- Should the visualisations (buttons vs circles) be an option for the content manager or included in the definition? Option in the content manager

**Acceptance criteria**

- [ ] Content managers can use interactive inputs in the storyline page and choose a visualisation type
- [ ] Modellers? can add interactive elements in the CMS and link the to the Anylogic settings
- [ ] Investigate if interactive elements can be filtered on a selected scenario in a storyline
- [ ] Interactive elements are continuous (Sliders), Single selects (radio, buttons), multiselects (checkbox, buttons)

**Comment by mattijsstam** [comment]
Question for UX, how does a user know if it is single select or multiselect

**Comment by pascalalferink** [comment]
Updated design:


![Image](https://user-images.githubusercontent.com/13336728/202653564-f3de7cce-24c1-498f-8df8-4017062d7046.png)

**Comment by pascalalferink** [comment]
With the current design the user doesn't see any slider values. For example: in the "Aandeel op zon" slider above  I assume this is a a slider with a range from 0 until 100. But because users can select a custom minimum and maximum value, this slider could also be a range from 46 until 943. I have Asked Kasper via Teams for an updated design

**Comment by pascalalferink** [comment]
Frontend has been made:

1. Checkboxes showns as checkboxes
2. Checkboxes shown as buttons
3. Radiobuttons shown as buttons
4. Radiobuttons shown as Radiobuttons

I re-used the current slider. Because of my remark aboven, I would lik te refactor this slider. For this, I have created a new issue: #186


While making this, I noticed, you can't set any of the options as default checked. [#187](https://github.com/ZEnMo/Holon-webapp/issues/187)

![Image](https://user-images.githubusercontent.com/13336728/202726072-a050730e-4bfb-4062-9639-0a2059c61c0b.png)
