### ISSUE TITLE
Quality improvements of the frontend code

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#31]
### Description

Due to the strict deadline some concessions have been made when it comes to the quality of code and the components developed in the frontend. This issue describes the technical debt of the frontend with the goal of fixing the issues before we continue the development of additional functionality.

### To discuss

@antw I really liked your code and component setup, can you go trough the frontend code and note the following things:

- Missing tests
- To large components
- Repetitive logic
- Wrong use of props vs state vs context
- And any other things you can think of

### Acceptance criteria

- [ ] All components have at least one unit test
- [ ] A component is at most ...lines of code?
- [ ] ???

**Comment by antw** [comment]
@mattijsstam I've looked through the code, and I think you've already hit on the main points in your message.

### Naming conventions

camelCase should be for variables and props and PascalCase for components and classes. For example:

  **Variables and props**

  ```
  inputid -> inputId
  updatevalue -> updateValue
  ```

  **Components**

  ```
  Scenarioresultitem -> ScenarioResultItem
  Scenarioswitch -> ScenarioSwitch
  ```

### Missing tests

Most of the components have no tests. This should be rectified for any components that...

  - ... have internal state (`useState`, `useReducer`)
  - ... have side-effects (`useEffect`)
  - ... handle events, either internally or by calling functions that are passed in as props
  - ... change their behaviour or appearance depending on props

Components which match these criteria are:

- [Scenarios/Neighbourhood](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/Neighbourhood.js)
- [Scenarios/Scenarioresultitem](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/Scenarioresultitem.js)
- [Scenarios/ScenarioResults](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/ScenarioResults.js) (help text changes depending on props)
- [Scenarios/Scenarioslider](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/Scenarioslider.js)
- [Scenarios/Scenarioswitch](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/Scenarioswitch.js)
- [Scenarios/Tooltip](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/Tooltip.js)
- [Scenarios](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios.js)
- [ContentBlock](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/ContentBlock.js)
- [TextBlock](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/TextBlock.js)

In my opinion components that are completely static don't _really_ need tests.

### Accessibility

- Consider changing [Scenarioswitch](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/Scenarioswitch.js) to use something like [@headlessui/react/switch](https://headlessui.com/react/switch), ensuring that the switch is useable by screen readers and other visitors with accessibility requirements.

### Code style

If you're using VS Code, [install the Prettier plugin](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and enable format on save. It'll automatically format your code each time you save, including ordering Tailwind classes.

Also consider [installing the ESLint plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint). The enabled React plugin will help catch mistakes.

[Other editors have equivalent plugins](https://prettier.io/docs/en/editors.html).

### Nitpicks

- [Scenarioswitch sets a conditional `className` with `&&`](https://github.com/ZEnMo/Holon-webapp/blob/ad68f96750e702068ff917bda60ec64aa05305f3/frontend/components/Scenarios/Scenarioswitch.js#L31). Although concise, this should be avoided because false-y operands will result in `"undefined"` being added to the class list.

  Prefer `something ? "cursor-not-allowed" : ""`. We might also consider [clsx](https://www.npmjs.com/package/clsx) if setting classes conditionally becomes a common pattern.

- Numerous JS errors in development mode due to PropType validation failing for `ScenarioResultItem`, `ScenarioResults`, `ScenarioSlider`

- [TextBlock](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/TextBlock.js) arguments should be called `props` for consistency with React. Alternatively, destructure the props.

- [Scenarios/Neighbourhood changes a prop value](https://github.com/ZEnMo/Holon-webapp/blob/ad68f96750e702068ff917bda60ec64aa05305f3/frontend/components/Scenarios/Neighbourhood.js#L7).

- [TextBlock `texts` and `createParagraphs`](https://github.com/ZEnMo/Holon-webapp/blob/ad68f96750e702068ff917bda60ec64aa05305f3/frontend/components/TextBlock.js#L14-L53) don't depend on the props and can be extracted out of the component. Same with [Scenario/Scenarioresultitem](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/Scenarioresultitem.js#L17-L85). There's an ESLint rule for this which I'll look for.

- If a component is made up of several sub-components, I tend to do one of two things:

  1. If the sub-components are simple, put them in the same file as the parent component. For example, SubscriptionForm [defines a custom SubmitButton](https://github.com/ZEnMo/Holon-webapp/blob/ad68f96750e702068ff917bda60ec64aa05305f3/frontend/components/FeedbackBlock/SubscriptionForm.js#L10-L30).

  2. If the sub-components are non-trivial, create a directory for the parent component and have the sub-components in separate files:

      ```
     ├ components
     │  ├ Sentiment
     │  │  ├ index.js        # contains the Sentiment component 
     │  │  ├ EmoticonButton  # contains an EmoticonButton component
     │  ├ ...
      ```

     Although it's hard to enforce, only components inside ./component/Sentiment are allowed to import EmoticonButton. Anything above the Sentiment directory should not import EmoticonButton. If it is general enough to be used by other components, move EmoticonButton up to ./components and rename files as appropriate:

      ```
     ├ components
     │  ├ EmoticonButton.js
     │  ├ Sentiment.js
     │  ├ ...
      ```

- Unnecessary tailwind bracket properties. For example:

  ```
  w-[1rem] -> w-4
  bottom-[100%] -> bottom-full
  right-[1rem] -> right-4
  ```

  Whenever possible, avoid `px` measurements and instead use Tailwinds [built-in size classes](https://tailwindcss.com/docs/width). When this is not possible, prefer to use `rem` measurements, as these will respect users' browser font-size preferences. Using built-in measurements will make it easier to transition to a responsive UI later.

- A [useEffect in Scenarios](https://github.com/ZEnMo/Holon-webapp/blob/c5ce9cdfc9810236921a5f6a31982b50f64ac956/frontend/components/Scenarios.js#L31-L40) is missing dependencies that are used in the function. There's an enabled ESLint rule for this.

- [ScenarioResults has a nested ternary operator](https://github.com/ZEnMo/Holon-webapp/blob/main/frontend/components/Scenarios/ScenarioResults.js#L81-L104) which is hard to read. Perhaps extract the help texts to a separate component?

- `for` and `htmlFor` are not needed when [the `input` is inside the `label` element](https://github.com/ZEnMo/Holon-webapp/blob/ad68f96750e702068ff917bda60ec64aa05305f3/frontend/components/Scenarios/Scenarioswitch.js#L20). Doing so will avoid the need to assign unique IDs to the label and input.

### Repetitive logic

There is a fair bit of repetition in some components, but it's mostly because of the lack of a backend. For example, in a finished app we might define the list of sliders in the backend and send them to the frontend via an API call. This would eliminate duplication in [Neighbourhood](https://github.com/ZEnMo/Holon-webapp/blob/ad68f96750e702068ff917bda60ec64aa05305f3/frontend/components/Scenarios/Neighbourhood.js#L16-L57). **However** we don't have such a backend, so I feel this duplication is justified.

**Comment by mattijsstam** [comment]
- [ ] Naming conventions
- [ ] Nitpicks
