### ISSUE TITLE
[holarchie] De gebruiker kan de KPI's in een overzicht zien per niveau (nationaal, lokaal en tussenniveau) in rechter deel (dashboard)

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#333]
![image](https://user-images.githubusercontent.com/78690362/217763507-e56ee718-02a8-4058-94f4-46895b7af191.png)

Discussiepunten:
1. Is er een reden waarom het nationale niveau actief lijkt te zijn, en de twee overige niveaus niet?
--> Nee, dat is vormgeving van Fleur. 

Vooralsnog werken we met dummy data voor het tussen niveau, dit wordt later dynamisch.

Acceptance:
- [ ] Het tussenniveau resultaten deel krijgt een titel (in ontwerp: 'res regio') o.b.v. instelling per casus (op dezelfde plek waar je afbeeldingen configureert = holarchie scherm config per casus pagina)
- [ ] Resultaten worden getoond per niveau voor de 4 indicatoren per sectie

**Comment by pascalalferink** [comment]
Is er een reden waarom het nationale niveau actief lijkt te zijn, en de twee overige niveaus niet?

**Comment by pascalalferink** [comment]
A start has been made: (see screenshots below)

1. kpi's are shown in a block
2. It uses most of the code from the current kpi's except for different styling
3. A title text was required for the middle section. I made this in Wagtail. As an extra I added a text area for the other 2 levels. The default for these text fields are "Nationaal", "Regionaal", "Lokaal".

To do's:
1. Colors aren't defined
2. Placement in grid layout
3. Currently there is no middle section because of a lack of data.


![Image](https://user-images.githubusercontent.com/13336728/218439232-e567e49f-d03a-4801-ab98-c42f0f173902.png)


![Image](https://user-images.githubusercontent.com/13336728/218440447-cc300a73-ce0b-408c-9b7a-c870ecc00638.png)

**Comment by pascalalferink** [comment]
![Image](https://user-images.githubusercontent.com/13336728/220039228-2fc8b19f-ce50-4731-a309-04b699fcde36.png)

Issue has been completed:
Note: the intermediate level is not shown, because there is no data.
