### ISSUE TITLE
Gebruikers kunnen op de detail pagina van de kosten/baten subgroepen selecteren en bekijken

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#493]
- [ ] Op detail wordt een dropdown getoond waarvan de data o.b.v. de "detail" keys gevuld wordt
- [ ] Grafiek/Tabel knoppen in detail pagina hebben een outline
- [ ] Animatie van tooltip weghalen in grafiek, gelijk maken aan tabel
- [ ] Padding onder Grafiek en Detail tab moet hetzelfde zijn als de pagina met detailknoppen
- [ ] 1e optie is default geselecteerd

![image](https://user-images.githubusercontent.com/78690362/227143682-fe21149b-ed39-43f7-81a0-296c3c177d82.png)

https://xd.adobe.com/view/bcb20e69-ef9c-46ec-8350-84981441c3b6-e9e1/screen/b0552878-2bbe-439b-b96c-3630929f60fc/

**Comment by mattijsstam** [comment]
Er wordt mij niet helemaal duidelijk wat de dropdown precies doet? wordt de grafiek hiermee aangepast?

**Comment by thesethtruth** [comment]
Dummy data:

Replace <data_object> with the original data object that the components can use already.

```json
{
    "dashboard_results": <dashboard_result_json>,
    "cost_benefit_results": {
        "overview": <data_object>,
        "detail": {
            "dropdown_label1" : <data_object1>,
            "dropdown_label2" : <data_object2>,
            "dropdown_label3" : <data_object3>,
            "dropdown_label4" : <data_object4>,
            "dropdown_label5" : <data_object5>,
        }
    },
}

```

**Comment by mattijsstam** [comment]
Detail resultaat is nog niet geimplementeerd in de backend dus zorgen voor foutafhandeling wanneer detail leeg is.

**Comment by pascalalferink** [comment]
@thesethtruth , er staat "1e optie is default geselecteerd" .
Zorg je ervoor dat deze eerste optie de algemene kosten-baten per categorie toont? Zo niet, hoe krijgt de gebruiker dan het algemene kostenoverzicht te zien?

**Comment by pascalalferink** [comment]
Detail has been implemented with static data:

1. Because the header "Kosten en baten per subcategorie"  is placed centered, the dropdown is being cut-off. This has been discussed with (and approved by) @kasperbosman 
2. Also @thesethtruth  mentioned the labels in the graph on the left side (Kosten Baten) were overlapping other texts in the y-axis. this has also been fixed within this issue.

Next step: wait until backed data is being provided. 


![image](https://github.com/ZEnMo/Holon-webapp/assets/13336728/6924a9f6-91e5-4cc2-8035-9c36b7e2898a)
