### ISSUE TITLE
When adding a template contract, the contractScope ID is not updated to the cloned value, breaking the link between contract and contractScope for anylogic

### ISSUE THREAD

**Issue by GillisHommen** [ZEnMo/Holon-webapp#625]
To change energy supplier of an actor, their existing DeliveryContract is removed and it is replaced by a template contract with the correct contractScope (see: https://pizzaoven.holontool.nl/wt/admin/holon/deliverycontract/586327/change/ )

However, when this template contract is added to the corresponding actors, the contractScope field (a FK) is not updated to the 'cloned' ID of the energysupplier:

![image](https://user-images.githubusercontent.com/98752265/232739647-4a62c1e7-04f3-45ec-ac3f-b158afc82ac4.png)

**Expected behavior**
When adding a template contract, the contractScope field should be updated to contain the correct FK of the (cloned) actor.

**Actual behavior**
The contractScope field of the template contract is not updated, which results in an error in Anylogic when it tries to make links between actors via contracts. (energy supplier can not be found)

**Comment by TAVMWB** [comment]
Issues still occur on pizzaoven, discussed with Gillis:
In his case, the contracts of 5 actors are removed. Then these 5 actors are filtered and contracts are added using the add rule action. However the anylogic json shows only 1 in 5 of these actors actually get this contract, and the contractscope for this contract is the original scenario's contractscope and not a cloned copy.
Maybe part of the cause of this problem is the fact that when the contracts are removed first, they also remove their contractscope according to the `CASCADE DELETE` rule as defined in the `Contract` model.
