### ISSUE TITLE
Debug slow hot reload times in the frontend

### ISSUE THREAD

**Issue by mattijsstam** [ZEnMo/Holon-webapp#75]

**Comment by antw** [comment]
@mattijsstam @MariaBee3 It turns out I _am_ experiencing this as well:

```
wait  - compiling...
event - compiled client and server successfully in 19.2s (543 modules)
```

This is weird... I can make a change in a much larger Next.js app and get this:

```
wait  - compiling...
event - compiled client and server successfully in 657 ms (2008 modules)
```

It was nearly two weeks ago that I last ran the app properly, so whatever it is must have happened since then. Would you like me to take a look at it? I could do so early next week.
