### ISSUE TITLE
Bug: kostenbaten can cause a crash if clicked before results are fetched

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#791]
**Describe the bug**
The button of kostenbaten can cause a client-side crash if clicked before results are fetched

**To Reproduce**
1. Go to acceptatie
2. Click the sandbox mode
3. Before the result is returned click on the kosten-baten button

**Screenshots**
![image](https://github.com/ZEnMo/Holon-webapp/assets/78690362/58bdd0f8-be11-4bdc-976f-8faca2dd8994)

**Comment by pascalalferink** [comment]
The application crashes because there are no details (yet).
I created fallbacks to prevent this from happening:

1. a loading state on the button "Kosten Baten" en "scenario opslaan"
2. on the kosten bate pagina, there is an extra check to see if there is data available (if not, a loading text is shown instead of crashing)
